version: 1
formatters:
  simple:
    format: "[PID:%(process)d] -- [%(levelname)s] -- [%(asctime)s.%(msecs)03d] -- [%(message)s]"
    datefmt: "%d-%m-%Y %H:%M:%S"

  debug:
    format: "[PID:%(process)d] -- [%(levelname)s] -- [%(asctime)s.%(msecs)03d] -- [%(filename)s:%(funcName)s:%(lineno)d] -- [%(message)s]"
    datefmt: "%d-%m-%Y %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: debug
    stream: ext://sys.stdout

  client_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/client/<timestamp>.log

  server_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/server/<timestamp>.log

  stream_server_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/server/stream/<timestamp>.log

loggers:
  client:
    level: DEBUG
    handlers: [console, client_file_handler]
    propagate: no

  server:
    level: DEBUG
    handlers: [console, server_file_handler]
    propagate: no

  stream_server:
    level: DEBUG
    handlers: [console, stream_server_file_handler]
    propagate: no
