version: 1
formatters:
  simple:
    format: '[%(levelname)s] -- [%(asctime)s] -- [%(filename)s:%(funcName)s:%(lineno)d] -- [%(message)s]'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/<timestamp>.log 
loggers:
  socket:
    level: DEBUG
    handlers: [console, file_handler] 
    propagate: no
  network:
    level: DEBUG
    handlers: [console, file_handler] 
    propagate: no
  timer:
    level: DEBUG
    handlers: [console, file_handler] 
    propagate: no
  client:
    level: DEBUG
    handlers: [console, file_handler] 
    propagate: no
root:
  level: DEBUG
  handlers: [console, file_handler] 
