version: 1
formatters:
  simple:
    format: "[PID:%(process)d] -- [%(levelname)s] -- [%(asctime)s.%(msecs)03d] -- [%(message)s]"
    datefmt: "%d-%m-%Y %H:%M:%S"
  debug:
    format: "[PID:%(process)d] -- [%(levelname)s] -- [%(asctime)s.%(msecs)03d] -- [%(filename)s:%(funcName)s:%(lineno)d] -- [%(message)s]"
    datefmt: "%d-%m-%Y %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/<timestamp>.log
loggers:
  socket:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

  network:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

  timer:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

  client:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

  server:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

  stream-server:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, file_handler]
